[package]
name = "angelio"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "Simple esolang with GPIO support"
repository = "https://github.com/zzanp/angelio"
readme = "README.md"

[dependencies]
rppal = "0.14.1"
